version: '3.3'

services:

  openvpn:
    build: .
    image: servercontainers/openvpn
    restart: always
    volumes:
      - ./config:/etc/openvpn
    privileged: true
#    cap_add:
#      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    networks:
      - ovpn

networks:
  ovpn:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
